import {
  MetricCardData,
  ScheduleItem,
  AssignmentItem,
  SmartRecommendation,
  AttendanceRecord,
  ProductivityDay,
  ConversationalFeedItem,
  AcademicSemesterTrend,
  SubjectStudyHours,
  UpcomingEvent,
  AcademicEvent,
} from "../types";

export const MOCK_METRICS: MetricCardData[] = [
  {
    id: "metric-academic",
    title: "ACADEMIC PERFORMANCE",
    value: "3.82 GPA",
    subtitle: "Target: 3.85 • Top 7% of Batch",
    trendText: "+0.08 vs Last Term",
    trendDirection: "up",
    statusVariant: "success",
    sparklineData: [3.6, 3.65, 3.72, 3.74, 3.79, 3.82],
    chartType: "line",
    iconKey: "academic",
    badgeText: "Top 7%",
  },
  {
    id: "metric-attendance",
    title: "ATTENDANCE RATE",
    value: "86.4%",
    subtitle: "Safe Margin: +11.4% above limit",
    trendText: "-1.8% this week",
    trendDirection: "down",
    statusVariant: "warning",
    sparklineData: [92, 90, 89, 88, 87, 86.4],
    chartType: "line",
    iconKey: "attendance",
    badgeText: "Safe Zone",
  },
  {
    id: "metric-assignments",
    title: "PENDING ASSIGNMENTS",
    value: "4 Due",
    subtitle: "2 In Review • 1 Critical Risk",
    trendText: "1 High Urgency",
    trendDirection: "neutral",
    statusVariant: "danger",
    sparklineData: [1, 2, 4, 3, 2, 4],
    chartType: "bar",
    iconKey: "assignments",
    badgeText: "1 Critical",
  },
  {
    id: "metric-placement",
    title: "PLACEMENT READINESS",
    value: "78%",
    subtitle: "Ready for Tier-1 Tech (IBM / Google)",
    trendText: "+5% vs Last Mo",
    trendDirection: "up",
    statusVariant: "purple",
    sparklineData: [62, 65, 68, 72, 75, 78],
    chartType: "line",
    iconKey: "placement",
    badgeText: "Tier-1 Ready",
  },
  {
    id: "metric-productivity",
    title: "PRODUCTIVITY",
    value: "34.5 hrs",
    subtitle: "Daily Avg: 4.9 hrs • 5d Streak",
    trendText: "+4.2 hrs vs Target",
    trendDirection: "up",
    statusVariant: "default",
    sparklineData: [24, 28, 30, 31, 32.5, 34.5],
    chartType: "line",
    iconKey: "productivity",
    badgeText: "5d Streak 🔥",
  },
];

export const MOCK_TODAYS_SCHEDULE: ScheduleItem[] = [
  {
    id: "sch-1",
    timeRange: "09:00 AM - 10:30 AM",
    title: "Operating Systems Lecture",
    type: "Lecture",
    location: "Hall B • Prof. Vance",
    mode: "In-Person",
    isUrgent: false,
  },
  {
    id: "sch-2",
    timeRange: "11:00 AM - 01:00 PM",
    title: "Database Systems Lab - Query Execution",
    type: "Lab",
    location: "Lab 03 • CS Dept",
    mode: "In-Person",
    isUrgent: true,
  },
  {
    id: "sch-3",
    timeRange: "02:30 PM - 03:30 PM",
    title: "CampusPilot AI Mentor Session (Sync)",
    type: "Mentor Sync",
    location: "Online (Virtual Room)",
    mode: "Online",
    isUrgent: false,
  },
  {
    id: "sch-4",
    timeRange: "04:00 PM - 06:00 PM",
    title: "Distributed Systems Self-Study & Revision",
    type: "Self-Paced Study",
    location: "Library Media Room 4A",
    mode: "Self-Study",
    isUrgent: false,
  },
];

export const MOCK_ASSIGNMENTS: AssignmentItem[] = [
  {
    id: "asg-1",
    courseCode: "CS501",
    subject: "Computer Networks",
    title: "TCP/IP Sliding Window Simulation",
    deadline: "Today, 04:00 PM",
    priority: "critical",
    status: "in_progress",
    estimatedHours: 2.5,
    riskLevel: "critical",
  },
  {
    id: "asg-2",
    courseCode: "CS503",
    subject: "Data Science & AI",
    title: "Multi-Class NLP Classification Pipeline",
    deadline: "Tomorrow, 11:59 PM",
    priority: "high",
    status: "todo",
    estimatedHours: 4.0,
    riskLevel: "high",
  },
  {
    id: "asg-3",
    courseCode: "CS502",
    subject: "Database Systems",
    title: "B+ Tree Indexing Engine & Query Optimization",
    deadline: "Sep 18, 11:59 PM",
    priority: "critical",
    status: "in_progress",
    estimatedHours: 5.0,
    riskLevel: "critical",
  },
  {
    id: "asg-4",
    courseCode: "CS505",
    subject: "Operating Systems",
    title: "Concurrency & Deadlock Prevention Lab",
    deadline: "Sep 22, 05:00 PM",
    priority: "high",
    status: "todo",
    estimatedHours: 3.5,
    riskLevel: "high",
  },
  {
    id: "asg-5",
    courseCode: "CS504",
    subject: "Cloud Architecture",
    title: "Fault Tolerant Microservices System Design",
    deadline: "Sep 25, 05:00 PM",
    priority: "medium",
    status: "todo",
    estimatedHours: 3.0,
    riskLevel: "moderate",
  },
  {
    id: "asg-6",
    courseCode: "CS599",
    subject: "Capstone Project",
    title: "System Architecture Document Submission",
    deadline: "Oct 02, 11:59 PM",
    priority: "low",
    status: "planning",
    estimatedHours: 6.0,
    riskLevel: "safe",
  },
  {
    id: "asg-7",
    courseCode: "CS501",
    subject: "Computer Networks",
    title: "Wireshark Packet Inspection & HTTP/3 Analysis",
    deadline: "Sep 10, 11:59 PM",
    priority: "medium",
    status: "completed",
    estimatedHours: 2.0,
    riskLevel: "safe",
  },
  {
    id: "asg-8",
    courseCode: "CS502",
    subject: "Database Systems",
    title: "SQL Relational Algebra Problem Set 3",
    deadline: "Sep 08, 05:00 PM",
    priority: "low",
    status: "completed",
    estimatedHours: 1.5,
    riskLevel: "safe",
  },
];

export const MOCK_SMART_RECOMMENDATIONS: SmartRecommendation[] = [
  {
    id: "rec-1",
    title: "Urgent Lab Submission & Attendance Warning",
    recommendation: "Prioritize your Database Systems Lab submission before 1:00 PM today to protect your 75% minimum course requirement.",
    reason: "Your current lab attendance stands at 73.5%. Missing today's evaluation triggers an automated academic advisory alert.",
    expectedImpact: "+2.5% course grade recovery and removes probationary status on Dean's List index.",
    category: "attendance",
    urgency: "critical",
    actionLabel: "Create Study Plan",
    timestamp: "10 mins ago",
    confidenceScore: 96,
    confidenceLevel: "High",
    confidenceReason: "High Confidence: Computed from real-time ERP biometric attendance logs & CS Dept Regulation 4.2.",
    whyThisRecommendation: {
      primaryTrigger: "Biometric swipe record indicates 14/19 sessions attended (73.68%), strictly below the 75.0% exam qualification threshold.",
      historicalContext: "Last semester, 89% of students with attendance < 75% in lab coursework faced grade penalties or remedial exams.",
      projectedOutcome: "Attending today's session raises attendance to 75.0%, preserving final examination eligibility.",
      dataSources: ["University ERP Biometrics", "CS502L Course Syllabus", "Academic Dean Regulations"],
      riskIfIgnored: "Mandatory departmental hearing and forfeiture of lab practical credits.",
    },
  },
  {
    id: "rec-2",
    title: "Spaced Repetition Revision for Operating Systems Midterm",
    recommendation: "Review Unit 3 (Process Synchronization & Semaphore Deadlocks) for 45 minutes this evening.",
    reason: "Exam countdown indicates 6 days remaining, and your concept mastery score on Semaphores is 62%.",
    expectedImpact: "Projected score improvement from 74% to 88% on section B of the exam.",
    category: "exam_prep",
    urgency: "high",
    actionLabel: "Create Study Plan",
    timestamp: "1 hour ago",
    confidenceScore: 92,
    confidenceLevel: "High",
    confidenceReason: "High Confidence: Inferred from mock quiz diagnostics and 3 past mid-semester question papers.",
    whyThisRecommendation: {
      primaryTrigger: "Topic diagnostic quiz on Sep 11 resulted in 3/5 errors on classic Dining Philosophers and Dekker's algorithm.",
      historicalContext: "Historical exam analysis shows 28% of Midterm points are allocated to Semaphore implementation and deadlock proofs.",
      projectedOutcome: "Targeted 45-minute practice session increases anticipated exam yield by 14 percentile points.",
      dataSources: ["Canvas Quiz Telemetry", "Past 3 Years OS Midterm Papers", "Cognitive Retention Curve"],
      riskIfIgnored: "High risk of scoring < 70% on Midterm Section B, affecting overall GPA target (3.80).",
    },
  },
  {
    id: "rec-3",
    title: "IBM Granite Hackathon & Career Portfolio Alignment",
    recommendation: "Complete Docker containerization for your CampusPilot project repository before the pitch round.",
    reason: "IBM Early Careers role criteria require verifiable experience in containerization and CI/CD pipelines.",
    expectedImpact: "+12% boost in Placement Readiness score for Cloud & AI Software Engineer roles.",
    category: "career",
    urgency: "medium",
    actionLabel: "Create Study Plan",
    timestamp: "3 hours ago",
    confidenceScore: 88,
    confidenceLevel: "High",
    confidenceReason: "High Confidence: Matched against 140+ IBM Software Engineering placement qualification matrices.",
    whyThisRecommendation: {
      primaryTrigger: "Campus recruiting criteria for Tier-1 Cloud & AI roles specifically require containerization artifact links.",
      historicalContext: "Candidates with containerized GitHub repos received 2.4x higher shortlist rates in previous campus placements.",
      projectedOutcome: "Increases Career Placement Readiness metric from 82% to 94% on university recruiting portal.",
      dataSources: ["IBM Early Careers Competency Matrix", "Placement Cell Past Records", "GitHub Repository Linter"],
      riskIfIgnored: "Missed priority shortlist window during IBM on-campus evaluation.",
    },
  },
  {
    id: "rec-4",
    title: "Computer Networks TCP Sliding Window Simulation",
    recommendation: "Allocate 2 uninterrupted hours this afternoon to complete the socket transmission buffer module.",
    reason: "Assignment #4 is due today at 04:00 PM; current progress is 65% complete with 2 unit tests failing.",
    expectedImpact: "Secures 100% on programming component, contributing 10% to final course grade.",
    category: "academic",
    urgency: "critical",
    actionLabel: "Create Study Plan",
    timestamp: "Just now",
    confidenceScore: 95,
    confidenceLevel: "High",
    confidenceReason: "High Confidence: Git commit logs & assignment deadline countdown within 3.5 hours.",
    whyThisRecommendation: {
      primaryTrigger: "Submission deadline at 04:00 PM today with pending ACK timeout retransmission tests.",
      historicalContext: "Late submissions in CS501 incur a 20% penalty per 24 hours.",
      projectedOutcome: "On-time submission preserves full 100 points.",
      dataSources: ["Git Commit History", "Canvas LMS Assignment Deadline API", "Course Late Policy"],
      riskIfIgnored: "20% late deduction reducing course grade from A to B-.",
    },
  },
];

export const MOCK_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  {
    subject: "Computer Networks",
    courseCode: "CS501",
    percentage: 88,
    attended: 22,
    total: 25,
    isCritical: false,
    color: "#0f62fe",
  },
  {
    subject: "Database Systems Lab",
    courseCode: "CS502L",
    percentage: 74,
    attended: 14,
    total: 19,
    isCritical: true,
    color: "#da1e28",
  },
  {
    subject: "Data Science & AI",
    courseCode: "CS503",
    percentage: 92,
    attended: 23,
    total: 25,
    isCritical: false,
    color: "#198038",
  },
  {
    subject: "Cloud Architecture",
    courseCode: "CS504",
    percentage: 84,
    attended: 21,
    total: 25,
    isCritical: false,
    color: "#8a3ffc",
  },
];

export const MOCK_PRODUCTIVITY_DAYS: ProductivityDay[] = [
  { day: "Mon", actualHours: 4.5, targetHours: 5.0, cognitiveLoad: 68 },
  { day: "Tue", actualHours: 6.2, targetHours: 5.0, cognitiveLoad: 82 },
  { day: "Wed", actualHours: 5.8, targetHours: 5.0, cognitiveLoad: 75 },
  { day: "Thu", actualHours: 7.1, targetHours: 5.5, cognitiveLoad: 90 },
  { day: "Fri", actualHours: 5.0, targetHours: 5.0, cognitiveLoad: 70 },
  { day: "Sat", actualHours: 3.5, targetHours: 4.0, cognitiveLoad: 50 },
  { day: "Sun", actualHours: 4.0, targetHours: 4.0, cognitiveLoad: 55 },
];

export const MOCK_CONVERSATIONAL_FEED: ConversationalFeedItem[] = [
  {
    id: "feed-1",
    source: "Bob AI - Academic",
    timestamp: "08:15 AM",
    badge: "Actionable",
    message: "I noticed you have 2 pending assignments due within 36 hours. I have scheduled a 2-hour focused study block at 04:00 PM today.",
    actionPrimaryText: "Accept Schedule",
    actionSecondaryText: "Reschedule",
  },
  {
    id: "feed-2",
    source: "Bob AI - Career Coach",
    timestamp: "Yesterday",
    badge: "Career Insight",
    message: "Your recent score in System Design (85%) places you in the top 10% of applicants for IBM Backend Engineer internships. Add this project to your resume?",
    actionPrimaryText: "Update Resume",
    actionSecondaryText: "Dismiss",
  },
];

export const MOCK_ACADEMIC_TREND: AcademicSemesterTrend[] = [
  {
    semester: "Sem 1",
    semesterNumber: 1,
    gpa: 3.52,
    cgpa: 3.52,
    departmentAverage: 3.35,
    creditsCompleted: 22,
  },
  {
    semester: "Sem 2",
    semesterNumber: 2,
    gpa: 3.65,
    cgpa: 3.58,
    departmentAverage: 3.40,
    creditsCompleted: 44,
  },
  {
    semester: "Sem 3",
    semesterNumber: 3,
    gpa: 3.71,
    cgpa: 3.63,
    departmentAverage: 3.42,
    creditsCompleted: 66,
  },
  {
    semester: "Sem 4",
    semesterNumber: 4,
    gpa: 3.78,
    cgpa: 3.67,
    departmentAverage: 3.46,
    creditsCompleted: 88,
  },
  {
    semester: "Sem 5 (Current)",
    semesterNumber: 5,
    gpa: 3.82,
    cgpa: 3.71,
    departmentAverage: 3.48,
    creditsCompleted: 110,
  },
];

export const MOCK_STUDY_HOURS: SubjectStudyHours[] = [
  {
    subject: "Database Systems",
    courseCode: "CS502",
    loggedHours: 10.5,
    targetHours: 12.0,
    color: "#0f62fe", // IBM Blue
  },
  {
    subject: "Computer Networks",
    courseCode: "CS501",
    loggedHours: 9.0,
    targetHours: 8.0,
    color: "#0072c3", // IBM Cyan/Blue
  },
  {
    subject: "OS & Concurrency",
    courseCode: "CS505",
    loggedHours: 8.5,
    targetHours: 10.0,
    color: "#8a3ffc", // IBM Purple
  },
  {
    subject: "Data Science & AI",
    courseCode: "CS503",
    loggedHours: 7.0,
    targetHours: 6.0,
    color: "#198038", // IBM Green
  },
  {
    subject: "Cloud Architecture",
    courseCode: "CS504",
    loggedHours: 5.5,
    targetHours: 6.0,
    color: "#005d5d", // IBM Teal
  },
];

export const MOCK_UPCOMING_EVENTS: UpcomingEvent[] = [
  {
    id: "evt-1",
    title: "Database Systems Lab - Attendance Critical",
    type: "Lecture",
    date: "Today, Sep 14",
    time: "11:00 AM - 01:00 PM",
    daysRemaining: 0,
    location: "Lab 03 • CS Dept",
    badgeVariant: "danger",
  },
  {
    id: "evt-2",
    title: "Computer Networks Assignment #4 Due",
    type: "Deadline",
    date: "Today, Sep 14",
    time: "04:00 PM",
    daysRemaining: 0,
    location: "Online Portal (Canvas)",
    badgeVariant: "warning",
  },
  {
    id: "evt-3",
    title: "Operating Systems Midterm Examination",
    type: "Exam",
    date: "Sep 20, 2026",
    time: "10:00 AM - 12:30 PM",
    daysRemaining: 6,
    location: "Auditorium Hall A",
    badgeVariant: "danger",
  },
  {
    id: "evt-4",
    title: "IBM Granite AI Hackathon & Pitch Day",
    type: "Hackathon",
    date: "Sep 24, 2026",
    time: "09:00 AM - 06:00 PM",
    daysRemaining: 10,
    location: "Innovation Hub / Virtual",
    badgeVariant: "purple",
  },
  {
    id: "evt-5",
    title: "Cloud Infrastructure & Kubernetes Workshop",
    type: "Workshop",
    date: "Sep 28, 2026",
    time: "02:00 PM - 04:30 PM",
    daysRemaining: 14,
    location: "Seminar Room 102",
    badgeVariant: "primary",
  },
];

export const MOCK_SCHEDULE_CALENDAR_DAYS = [
  { id: "cal-14", day: 14, dayName: "Mon", isToday: true, isSelected: true, eventsCount: 4, hasDeadline: true },
  { id: "cal-15", day: 15, dayName: "Tue", eventsCount: 3, hasDeadline: false },
  { id: "cal-16", day: 16, dayName: "Wed", eventsCount: 2, hasDeadline: false },
  { id: "cal-17", day: 17, dayName: "Thu", eventsCount: 3, hasDeadline: true },
  { id: "cal-18", day: 18, dayName: "Fri", eventsCount: 2, hasDeadline: false },
  { id: "cal-19", day: 19, dayName: "Sat", eventsCount: 1, hasDeadline: false },
  { id: "cal-20", day: 20, dayName: "Sun", eventsCount: 2, hasExam: true },
];

export const MOCK_ACADEMIC_EVENTS: AcademicEvent[] = [
  // DEADLINES
  {
    id: "evt-dl-1",
    title: "TCP/IP Sliding Window Protocol Simulation",
    type: "Deadline",
    category: "deadline",
    courseCode: "CS501",
    courseName: "Computer Networks",
    date: "2026-09-14",
    displayDate: "Today, Sep 14",
    time: "04:00 PM",
    location: "Canvas LMS Submission Portal",
    daysRemaining: 0,
    urgency: "critical",
    description: "Submit C++ socket programming simulation with ACK timeout sliding window protocol & unit test logs.",
    weightage: "10% of Course Grade",
    syllabusOrTopics: ["TCP Handshake", "Sliding Window", "Go-Back-N Protocol", "Checksum Validation"],
    status: "in_progress",
  },
  {
    id: "evt-dl-2",
    title: "Multi-Class NLP Classification Pipeline",
    type: "Deadline",
    category: "deadline",
    courseCode: "CS503",
    courseName: "Data Science & AI",
    date: "2026-09-15",
    displayDate: "Tomorrow, Sep 15",
    time: "11:59 PM",
    location: "Kaggle Classroom & Canvas",
    daysRemaining: 1,
    urgency: "high",
    description: "Submit fine-tuned Transformer model notebook achieving >= 85% F1-score on legal text dataset.",
    weightage: "15% of Course Grade",
    syllabusOrTopics: ["HuggingFace Transformers", "BERT Tokenization", "Precision/Recall Optimization"],
    status: "upcoming",
  },
  {
    id: "evt-dl-3",
    title: "B+ Tree Indexing Engine & Query Optimizer",
    type: "Deadline",
    category: "deadline",
    courseCode: "CS502",
    courseName: "Database Systems",
    date: "2026-09-18",
    displayDate: "Sep 18, 2026",
    time: "11:59 PM",
    location: "GitHub Classroom Auto-Grader",
    daysRemaining: 4,
    urgency: "critical",
    description: "Implement page splitting, node merging, and concurrency latches for disk-backed B+ tree index.",
    weightage: "15% of Course Grade",
    syllabusOrTopics: ["Disk Page Layout", "B+ Tree Invariants", "Two-Phase Locking (2PL)"],
    status: "upcoming",
  },
  {
    id: "evt-dl-4",
    title: "Deadlock Prevention & Concurrency Lab Report",
    type: "Deadline",
    category: "deadline",
    courseCode: "CS505",
    courseName: "Operating Systems",
    date: "2026-09-22",
    displayDate: "Sep 22, 2026",
    time: "05:00 PM",
    location: "OS Lab Submissions Drop",
    daysRemaining: 8,
    urgency: "high",
    description: "Benchmark Dekker vs. Peterson vs. POSIX Mutex performance under 16 concurrent worker threads.",
    weightage: "12% of Course Grade",
    syllabusOrTopics: ["Critical Sections", "Deadlock Bank's Algorithm", "Cache Contention"],
    status: "upcoming",
  },
  {
    id: "evt-dl-5",
    title: "Capstone System Architecture & Threat Model",
    type: "Deadline",
    category: "deadline",
    courseCode: "CS599",
    courseName: "Senior Capstone Project",
    date: "2026-10-02",
    displayDate: "Oct 02, 2026",
    time: "11:59 PM",
    location: "Department Capstone Portal",
    daysRemaining: 18,
    urgency: "medium",
    description: "Detailed C4 architecture diagrams, STRIDE threat analysis, and microservices schema specification.",
    weightage: "20% of Project Grade",
    syllabusOrTopics: ["C4 Model", "STRIDE Threat Modeling", "OpenAPI Specifications"],
    status: "upcoming",
  },

  // EXAMS
  {
    id: "evt-ex-1",
    title: "Database Systems Practical Lab Exam",
    type: "Exam",
    category: "exam",
    courseCode: "CS502L",
    courseName: "Database Systems Laboratory",
    date: "2026-09-17",
    displayDate: "Sep 17, 2026",
    time: "10:00 AM - 01:00 PM",
    location: "Computing Lab 03 • CS Dept",
    daysRemaining: 3,
    urgency: "critical",
    description: "Live 3-hour practical SQL tuning, schema normalization, and index benchmark exam.",
    weightage: "20% of Final Practical Grade",
    syllabusOrTopics: ["Complex SQL Aggregations", "Query Plan EXPLAIN ANALYZE", "Transactions & ACID", "Trigger Functions"],
    status: "upcoming",
  },
  {
    id: "evt-ex-2",
    title: "Operating Systems Mid-Semester Examination",
    type: "Exam",
    category: "exam",
    courseCode: "CS505",
    courseName: "Operating Systems & Concurrency",
    date: "2026-09-20",
    displayDate: "Sep 20, 2026",
    time: "10:00 AM - 12:30 PM",
    location: "Engineering Auditorium Hall A",
    daysRemaining: 6,
    urgency: "critical",
    description: "Comprehensive mid-semester written examination covering Units 1 through 3.",
    weightage: "30% of Total Course Grade",
    syllabusOrTopics: ["Process Scheduling Algorithms", "Virtual Memory & Page Replacement", "Synchronization Primitives", "Dining Philosophers Problem"],
    status: "upcoming",
  },
  {
    id: "evt-ex-3",
    title: "Computer Networks Mid-Term Theory Evaluation",
    type: "Exam",
    category: "exam",
    courseCode: "CS501",
    courseName: "Computer Networks",
    date: "2026-09-26",
    displayDate: "Sep 26, 2026",
    time: "02:00 PM - 04:30 PM",
    location: "Science Block Lecture Hall B",
    daysRemaining: 12,
    urgency: "high",
    description: "In-depth theoretical examination on protocol layers, congestion control, and subnetting.",
    weightage: "25% of Total Course Grade",
    syllabusOrTopics: ["CIDR Subnetting", "Dijkstra Link-State Routing", "TCP BBR vs. Reno", "TLS 1.3 Handshake Security"],
    status: "upcoming",
  },
  {
    id: "evt-ex-4",
    title: "Data Science & AI Diagnostic Mock Test",
    type: "Exam",
    category: "exam",
    courseCode: "CS503",
    courseName: "Data Science & AI",
    date: "2026-09-29",
    displayDate: "Sep 29, 2026",
    time: "09:00 AM - 10:30 AM",
    location: "Classroom 404 & LMS Online",
    daysRemaining: 15,
    urgency: "medium",
    description: "Departmental midterm preparatory test covering mathematical statistics and ML fundamentals.",
    weightage: "10% of Internal Assessment",
    syllabusOrTopics: ["Matrix Decompositions (SVD)", "Gradient Descent Variants", "Bayesian Optimization", "Regularization (L1/L2)"],
    status: "upcoming",
  },

  // CAREER EVENTS
  {
    id: "evt-cr-1",
    title: "IBM Early Careers Pre-Placement Talk & Q&A",
    type: "Career",
    category: "career",
    companyOrHost: "IBM Cloud & AI Systems",
    date: "2026-09-16",
    displayDate: "Sep 16, 2026",
    time: "05:00 PM - 07:00 PM",
    location: "Main University Auditorium & Live Stream",
    daysRemaining: 2,
    urgency: "high",
    description: "Direct interaction with IBM hiring directors on Software Engineer, Cloud Architect, and AI Research roles.",
    weightage: "Mandatory for Placement Eligibility",
    syllabusOrTopics: ["IBM Granite Model Stack", "Enterprise Containerization", "Hiring Process & Coding Assessment Criteria"],
    status: "upcoming",
  },
  {
    id: "evt-cr-2",
    title: "IBM Granite AI Hackathon & Pitch Competition",
    type: "Career",
    category: "career",
    companyOrHost: "IBM Client Engineering",
    date: "2026-09-24",
    displayDate: "Sep 24, 2026",
    time: "09:00 AM - 06:00 PM",
    location: "Tech Innovation Hub / Virtual Arena",
    daysRemaining: 10,
    urgency: "critical",
    description: "24-hour hackathon building enterprise student success copilots. Top 3 teams receive fast-track interview rounds.",
    weightage: "+12% Placement Readiness Boost",
    syllabusOrTopics: ["WatsonX / Granite SDK", "Fullstack React Deployment", "Explainable AI Architecture"],
    status: "upcoming",
  },
  {
    id: "evt-cr-3",
    title: "Google Cloud Career Readiness Tech Summit",
    type: "Career",
    category: "career",
    companyOrHost: "Google Cloud Education",
    date: "2026-09-27",
    displayDate: "Sep 27, 2026",
    time: "03:00 PM - 05:00 PM",
    location: "Virtual Webcast & Student Lounge",
    daysRemaining: 13,
    urgency: "medium",
    description: "Hands-on session on Kubernetes, Cloud Run containerization, and associate engineer certifications.",
    weightage: "Free Cloud Certification Voucher",
    syllabusOrTopics: ["Google Cloud Run", "Microservices Networking", "Cloud Architecture Certifications"],
    status: "upcoming",
  },
  {
    id: "evt-cr-4",
    title: "Amazon AWS SDE Mock Technical Interview Round 1",
    type: "Career",
    category: "career",
    companyOrHost: "Alumni In Tech Mentorship",
    date: "2026-10-05",
    displayDate: "Oct 05, 2026",
    time: "01:00 PM - 03:00 PM",
    location: "Career Center Interview Booth 4B",
    daysRemaining: 21,
    urgency: "high",
    description: "1-on-1 mock algorithmic interview with senior Amazon engineers including live whiteboarding feedback.",
    weightage: "Interview Readiness Assessment",
    syllabusOrTopics: ["Dynamic Programming", "Graph Traversals (BFS/DFS)", "Amazon Leadership Principles"],
    status: "upcoming",
  },
  {
    id: "evt-cr-5",
    title: "Campus Placement Portal Registration Cutoff",
    type: "Career",
    category: "career",
    companyOrHost: "University Placement Cell",
    date: "2026-10-10",
    displayDate: "Oct 10, 2026",
    time: "11:59 PM",
    location: "Official University Placement Portal",
    daysRemaining: 26,
    urgency: "critical",
    description: "Final deadline to upload verified transcripts, resume PDF, and GitHub repository links for Tier-1 companies.",
    weightage: "Strict University Cutoff",
    syllabusOrTopics: ["Resume Verification", "Transcript Audit", "Company Application Bidding"],
    status: "upcoming",
  },
];
